package com.myspace.bc_training;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FamilyVisaApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int applicationId;
	private java.util.List<java.lang.String> passportNumbers;
	private java.time.LocalDate visitStartDate;
	private java.time.LocalDate visitEndDate;

	public FamilyVisaApplication() {
	}

	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	public java.util.List<java.lang.String> getPassportNumbers() {
		return this.passportNumbers;
	}

	public void setPassportNumbers(
			java.util.List<java.lang.String> passportNumbers) {
		this.passportNumbers = passportNumbers;
	}

	public java.time.LocalDate getVisitStartDate() {
		return this.visitStartDate;
	}

	public void setVisitStartDate(java.time.LocalDate visitStartDate) {
		this.visitStartDate = visitStartDate;
	}

	public java.time.LocalDate getVisitEndDate() {
		return this.visitEndDate;
	}

	public void setVisitEndDate(java.time.LocalDate visitEndDate) {
		this.visitEndDate = visitEndDate;
	}

	public FamilyVisaApplication(int applicationId,
			java.util.List<java.lang.String> passportNumbers,
			java.time.LocalDate visitStartDate, java.time.LocalDate visitEndDate) {
		this.applicationId = applicationId;
		this.passportNumbers = passportNumbers;
		this.visitStartDate = visitStartDate;
		this.visitEndDate = visitEndDate;
	}
	
    public static String join(java.util.Collection<java.lang.String> collection) {
      return collection.stream()
        .map(Object::toString)
        .collect(java.util.stream.Collectors.joining(","));
    }

  @Override
  public java.lang.String toString() {
    return java.lang.String.format("FamilyVisaApplication[#%d, %s]", applicationId, join(passportNumbers));
  }
	

}