package com.myspace.bc_training;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GroupLeader implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.myspace.bc_training.Passport passport;
	public GroupLeader() {
	}

	public com.myspace.bc_training.Passport getPassport() {
		return this.passport;
	}

	public void setPassport(com.myspace.bc_training.Passport passport) {
		this.passport = passport;
	}

	public GroupLeader(com.myspace.bc_training.Passport passport) {
		this.passport = passport;
	}

}