package com.myspace.bc_training;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InvalidPassport implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.myspace.bc_training.Passport passport;

	public InvalidPassport() {
	}

	public com.myspace.bc_training.Passport getPassport() {
		return this.passport;
	}

	public void setPassport(com.myspace.bc_training.Passport passport) {
		this.passport = passport;
	}

	public InvalidPassport(com.myspace.bc_training.Passport passport) {
		this.passport = passport;
	}
	
	@Override
    public java.lang.String toString() {
       return "Invalid" + this.passport;
    }

}