package com.myspace.bc_training;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InvalidFamilyVisaApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.myspace.bc_training.FamilyVisaApplication familyVisaApplication;

	public InvalidFamilyVisaApplication() {
	}

	public com.myspace.bc_training.FamilyVisaApplication getFamilyVisaApplication() {
		return this.familyVisaApplication;
	}

	public void setFamilyVisaApplication(
			com.myspace.bc_training.FamilyVisaApplication familyVisaApplication) {
		this.familyVisaApplication = familyVisaApplication;
	}

	public InvalidFamilyVisaApplication(
			com.myspace.bc_training.FamilyVisaApplication familyVisaApplication) {
		this.familyVisaApplication = familyVisaApplication;
	}
	
    @Override
    public java.lang.String toString() {
       return "Invalid:" + familyVisaApplication;
    }

}