package com.myspace.bc_training;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidVisaApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.myspace.bc_training.VisaApplication visaApplication;

	public ValidVisaApplication() {
	}

	public com.myspace.bc_training.VisaApplication getVisaApplication() {
		return this.visaApplication;
	}

	public void setVisaApplication(
			com.myspace.bc_training.VisaApplication visaApplication) {
		this.visaApplication = visaApplication;
	}

	public ValidVisaApplication(
			com.myspace.bc_training.VisaApplication visaApplication) {
		this.visaApplication = visaApplication;
	}
	
    @Override
    public java.lang.String toString() {
       return "Valid" + visaApplication;
    }

}