package com.myspace.bc_training;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Visa implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String passportNumber;

	public Visa() {
	}

	public java.lang.String getPassportNumber() {
		return this.passportNumber;
	}

	public void setPassportNumber(java.lang.String passportNumber) {
		this.passportNumber = passportNumber;
	}

	public Visa(java.lang.String passportNumber) {
		this.passportNumber = passportNumber;
	}
	
    @Override
    public java.lang.String toString() {
       return "Visa[passport:" + passportNumber + "]";
    }

}