package com.myspace.drools_training_master;

import com.myspace.bc_training.Passport;
import com.myspace.bc_training.InvalidPassport;
import com.myspace.bc_training.InvalidFamilyVisaApplication;
import com.myspace.bc_training.FamilyVisaApplication;

import java.time.LocalDate;

rule "Invalidate visa applications with invalid passport"
	dialect "mvel"
	when
		$familyVisaApplication: FamilyVisaApplication( )
		InvalidPassport( $familyVisaApplication.passportNumbers.contains(this.passport.passportNumber) )
	then
		System.out.println( "Set " + $familyVisaApplication + " invalid as it contains invalid passport");
		insert( new InvalidFamilyVisaApplication($familyVisaApplication) )
end