package com.myspace.drools_training_master;


import com.myspace.bc_training.InvalidFamilyVisaApplication;
import com.myspace.bc_training.FamilyVisaApplication;
import com.myspace.bc_training.Visa;

import java.time.LocalDate;

rule "Issue visas for valid applications"
	dialect "mvel"
	when
		$familyVisaApplication: FamilyVisaApplication( )
		not ( InvalidFamilyVisaApplication( this.familyVisaApplication == $familyVisaApplication ) )
	then
		for (String passportNumber : $familyVisaApplication.getPassportNumbers()) {
		  System.out.println( "Issue visa for passport number " + passportNumber);
		  insertLogical( new Visa( passportNumber ) )
		}
end